#!/usr/bin/env bash
# Build script for MagicMirrorOS
# Where the MagicMirror magic happens
# Written by Guy Sheffer and Karsten Hassel
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

apt-get update
apt-get install -y git ca-certificates curl

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

apt-get clean
rm -rf /var/lib/apt/lists/*

usermod -aG docker "${BASE_USER}"

chown "${BASE_USER}":"${BASE_USER}" /opt
gitclone MM_REPO /opt/mm

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

chmod +x /usr/bin/start_mm /usr/bin/stop_mm

systemctl enable mm.service
