#!/usr/bin/env bash
# Build script for MagicMirrorOS
# Where the MagicMirror magic happens
# Written by Guy Sheffer
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /opt/custompios "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /"${BASE_BOOT_MOUNT_PATH}"

apt-get update
apt-get install -y unclutter git

# add user pi to docker
usermod -aG docker pi

echo "WantedBy=graphical.target" >> /lib/systemd/system/docker.service

# add git repo check to .bashrc
echo "source /home/pi/scripts/check_git_repo" >> /home/pi/.bashrc

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

#cleanup
apt-get clean
apt-get autoremove -y
