#!/bin/bash

if [ ! -f /home/pi/magicmirror/run/docker-compose.yml ]; then
  cd /home/pi/
  git clone https://gitlab.com/khassel/magicmirror.git
  cd magicmirror/run
  cp rpi.yml docker-compose.yml
  mkdir -p /home/pi/magicmirror/mounts
fi
cd /home/pi/magicmirror/run
# start mm
docker-compose up -d
# pull newest docker image
docker-compose pull
# restart if image changed
docker-compose up -d
# delete old images
docker image prune -f

sleep infinity
#xterm
# while true
# do
#     sleep 10
# done
