#!/bin/bash

_log=$HOME/scripts/start.log
echo "---------log-of-run_magicmirroros---------" > $_log

if [ ! -f $HOME/magicmirror/run/docker-compose.yml ]; then
  sudo update-ca-certificates &>> $_log
  _curl=1
  until [ $_curl -eq 0 ]
  do
    curl -f -L -s https://gitlab.com
    _curl=$?
    if [ ! $_curl -eq 0 ]; then
      echo "cannot connect to gitlab.com ..." &>> $_log
      sleep 5s
    fi
  done
  cd $HOME/
  rm -rf magicmirror
  git clone https://gitlab.com/khassel/magicmirror.git &>> $_log
  cd magicmirror/run
  cp -v rpi.yml docker-compose.yml &>> $_log
  mkdir -p $HOME/magicmirror/mounts
else
  cd $HOME/magicmirror/run
  # update git repo
  git fetch
fi
# start mm
docker-compose up -d &>> $_log
# pull newest docker image
docker-compose pull &>> $_log
# restart if image changed
docker-compose up -d &>> $_log
# delete old images
docker image prune -f &>> $_log
# disable wlan power save
sudo iw wlan0 set power_save off

sleep infinity
